### PR TITLE
Fix crash on Forge 33.0.21+, fix dev environment

### PR DESCRIPTION
**Pull request by PaintNinja**
Should work on Forge 33.0.21 for 1.16.2 all the way up to the latest Forge for 1.16.5 now.

### CODE REVIEW

**Comment by agentwolf88** [comment]
Where can i download the patched .jar file?

**Comment by PaintNinja** [comment]
Here you go: https://github.com/PaintNinja/Locks/releases/tag/v2.5.3

**Comment by agentwolf88** [comment]
Nice! THX

**Comment by PaintNinja** [comment]
BWAAAAAA
image

**Comment by MercurialPony** [comment]
Thanks, no longer necessary

**Pull request closed without merging**
